AppOrder/urls.py
from django.urls import path
app_name = 'AppOrder'
from AppOrder import views

urlpatterns = [
    
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('cart/',views.cart_view,name='cart'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),


]

AppShop/urls.py
from django.urls import path
from AppShop import views


app_name = 'AppShop'


urlpatterns = [

	path('',views.Home.as_view(),name='home'),
	path('product/<pk>/',views.ProductDetail.as_view(),name='product_detail')
]

MyEcomProject/urls.py
from django.contrib import admin
from django.urls import path,include

#To show media files


from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppShop.urls')),
    path('account/',include('AppLogin.urls')),
    path('shop/',include('AppOrder.urls')),
    path('payment/',include('AppPayment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppShop/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
	title = models.CharField(max_length=20)
	created = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.title


	class Meta:
		verbose_name_plural = "Category"



class Product(models.Model):
	mainimage = models.ImageField(upload_to='Products')
	name = models.CharField(max_length=260)
	category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category')
	preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
	detail_text = models.TextField(max_length=1000,verbose_name='Description')
	price = models.FloatField()
	old_price = models.FloatField()
	created = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.name


	class Meta:
		#jeta k age create kora hobe seta upore dekha be,ar porer ta pore dekhabe
		ordering = ['-created',]

AppShop/views.py
from django.shortcuts import render

#Import Views
from django.views.generic import ListView,DetailView


#Models
from AppShop.models import Product


#Mixin
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

class Home(ListView):
	model = Product
	template_name = 'AppShop/home.html'



class ProductDetail(LoginRequiredMixin,DetailView):
	model = Product
	template_name = 'AppShop/product_details.html'

templates/AppShop/home.html
 {% extends 'base.html' %}

{% block body_block %}

<div class="container my-5">
	<h2 class="my-5">Featured Products</h2>
	<div class="row">
		{% for product in object_list %}
		<div class="col-md-6 col-sm-12 col-lg-3">
			<figure class="card card-product">
				<div class="img-wrap">
					<img src="/media/{{product.mainimage}}" style="width:100%; height: 300px;">

				</div>
				<figure class="info-wrap">
					<h6 class="title"><a href=" {% url 'AppShop:product_detail' pk=product.pk %} ">{{product.name}}</a></h6>
					
					<div class="action-wrap">
						<div class="price-wrap h5">
							<span class="price-new">&#2547;{{product.price|floatformat:2}}</span>
							<span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
						</div>
					</div>
				</figure>
			</figure>
		</div>
		{% endfor %}
	</div>
	
</div>

	

{% endblock %}

templates/AppShop/product_details.html
  {% extends 'base.html' %}
  {% block body_block%}

  	<div class="container my-5">
  		<div class="cart">
  			<div class="row">
  				<aside class="col sm-5 border-right">
  					<article class="gallery-wrap">
  						<div class="img-big-wrap">
  							<div class="">
  								<a href=""><img src="/media/{{object.mainimage}}" style="width:450px"></a>
  							</div>
  						</div>
  						
  					</article>
  				</aside>
  				<aside class="col sm-7">
  					<article class="cart-body p-5">
  						<h3 class="title mp-3">{{object.name}}</h3>
                        <p> {object.preview_text} </p>
  						<p class="price-detail-wrap">
  							<span class="price h3 text-warning">
  								<span class="currency">
  								BTD &#2547;<span class="num">{{object.price}}</span>	
  								</span>
  							</span>
  						</p>
  						<dl class="item-property">
  							<dt>Description
  							</dt>
  								<dd>
  									<p>{{object.detail_text|linebreaks}}</p>
  								</dd>
  						</dl>
  						<a href="{% url 'AppOrder:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
  					</article>
  				</aside>
  				
  			</div>
  		</div>
  	</div>

  {% endblock %}