AppLogin/urls.py
from django.urls import path
from AppLogin import views



app_name = 'AppLogin'


urlpatterns = [

	path('signup/',views.sign_up,name='signup'),
	path('login/',views.login_user,name='login'),
	path('logout/',views.logout_user,name='logout'),
	path('profile/',views.user_profile,name='profile'),

]

AppOrder/urls.py
from django.urls import path
app_name = 'AppOrder'
from AppOrder import views

urlpatterns = [
    
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('cart/',views.cart_view,name='cart'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),


]

AppShop/urls.py
from django.urls import path
from AppShop import views


app_name = 'AppShop'


urlpatterns = [

	path('',views.Home.as_view(),name='home'),
	path('product/<pk>/',views.ProductDetail.as_view(),name='product_detail')
]

MyEcomProject/urls.py
from django.contrib import admin
from django.urls import path,include

#To show media files


from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppShop.urls')),
    path('account/',include('AppLogin.urls')),
    path('shop/',include('AppOrder.urls')),
    path('payment/',include('AppPayment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<style>
@import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;1,200&display=swap');
</style>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{% block title_block %} E-com | Owner {% endblock %}</title>
	<style>
	.card {
		height: 350px;
	}

	.card-product:after {
		content: "";
		display: table;
		clear: both;
		visibility: hidden;
	}
	.card-product .price_new, .card-product .price{
		margin-right: #999;
	}
	.card-product .price-old {
		color: #999;
	}
	.card-product .img-wrap {
		border-radius: 3px 3px 0 0;
		overflow: hidden;
		position: relative;
		height: 220px;
		text-align: center;

	}

	.card-product .img-wrap img {
		max-height: 100%;
		max-width: 100%;
		object-fit: cover;

	}

	/*.card-product .img-wrap:hover {
		transform: scale(1.2);
		z-index: 4;
	}
*/

	.card-product .info-wrap {
		overflow: hidden;
		padding-top: 15px;
		border-top: 1px solid #eee;
	}

	.card-product .action-wrap {
		padding-top: 4px;
		margin-top: 4px;
	}

	.card-product .bottom-wrap {
		padding: 15px;
		border-top: 1px solid #eee;
	}

	.card-product .title {
		margin-top: 0px;
	}
		
	</style>
	
	
	
	
	
	
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<body>
	{% include 'navbar.html' %}
	<div class="container" style="padding-top: 15px;">
		<div class="messages container mt-2">

			{% if messages %}
			{% for message in messages %}
				<div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">

					{{message}}
					<button type="button" class="close" data-dismiss="alert" aria-lebel="close"><span aria-hidden="true">&times;</span></button>
					
				</div>
					
			{% endfor %}
			{% endif %}
		</div>
		{% block body_block %}
		{% endblock %}
			
	</div>

</body>
</html>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>


<!-- separete -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

templates/navbar.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	<div class="container">
		<a class="navbar-brand" href="{% url 'AppShop:home' %}"><p><i><b>Online Super Shop</i></b></p></a>
		<button type="button" class="navbar-toggler" data-toggler="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
			
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				 {% if request.user.is_authenticated %}
				<li class="nav-item" >
					<a href=" {% url 'AppOrder:cart' %} " class="nav-link"><i class="fa fa-shopping-cart"></i>Cart
					<span class="badge badge-light"> {{ request.user | cart_total }} </span>
					</a>
					
					</li>
					<li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-tie"></i>
			         {{request.user.profile.username}}
			        </a>
			        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			          <a class="dropdown-item" href="{% url 'AppLogin:profile' %}">Profile</a>
			          <a class="dropdown-item" href="#">Order</a>
			          <div class="dropdown-divider"></div>
			          <a class="dropdown-item" href="{% url 'AppLogin:logout' %}">Logout</a>
			        </div>
		        </li>
      {% else %}
      <li class="nav-item">
      	<a href="{% url 'AppLogin:login' %}" class="btn btn-primary">Login</a>
      </li>
      <li class="nav-item">
      	<a href="{% url 'AppLogin:signup' %}" class="btn btn-primary">Registration</a>
      </li>
      {% endif %}
			</ul>
      
		</div>
		
	</div>
	
</nav>

templates/success.html
{% extends 'base.html' %}

{% block body_block %}
<!-- <br>
<br>
<br>
<br>
<br>
<br> -->
	<div class="alert alert-info" align="center">
		<h2>You Are Successfully Checked Out!!</h2>
	</div>


{% endblock %}